Update MDSD, MDM image coordinates
openshift/installer-aro-wrapper pull request #143
Opened 2024-07-24 14:53 UTC by s-fairchild

For [ARO-5049](https://issues.redhat.com/browse/ARO-5049)

Update MDM, MDSD image coordinates.

2024-07-26 06:22 UTC, jaitaiwan approved these changes
LGTM

2024-07-29 18:26 UTC, tsatam commented on pkg/util/version/const.go
> +	return acrDomain + "/distroless/genevamdsd:mariner_20240711.1@sha256:20266be8d3de71ceaf6b864e70e295de5eecb5f796aad92bc303efcaf179a365"
This needs to be updated to the correct distroless coordinate: 
```suggestion
	return acrDomain + "/distroless/genevamdsd:mariner_20240711.1@sha256:86d73d9df70aca71c54bbfbdf6402a2cc1ddd9cbbebf3d6a0319de5950b10382"
```

2024-07-29 18:26 UTC, tsatam requested changes
MDSD coordinate needs to be updated to the correct digest.

2024-07-29 18:29 UTC, tsatam approved these changes

2024-09-25 00:14 UTC, hlipsig approved these changes
LGTM

2024-09-25 00:39 UTC, merged